# config/packages/tzunghaor_settings.yaml
tzunghaor_settings:
  collections:
    # Each entry under "tzunghaor_settings" configures a setting collection.
    global:
#      cache: 'cache.app'
      mappings:
        # I used "default" as mapping name, but it is up to you.
        # You can have multiple mappings
        default:
          dir: '%kernel.project_dir%/src/Settings/Global'
          prefix: App\Settings\Global\

framework:
  # the form is not saving, due to default symfony configuration
  # https://github.com/tzunghaor/settings-bundle/issues/3
  # https://github.com/symfony/symfony/issues/45278
#  http_method_override: true