name: encounterthecross
services:
#  database:
#    image: 'mysql:latest'
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: main
##        ports:
#      # To allow the host machine to access the ports below, modify the lines below.
#      # For example, to allow the host to connect to port 3306 on the container, you would change
#      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
#      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
##            - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64  # Add this if you're on ARM64 architecture
    environment:
      PMA_HOST: hostgatordatabase
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '8080:80'
    depends_on:
      - hostgatordatabase
    restart: unless-stopped
  hostgatordatabase:
    image: 'mysql:5.7'
    platform: linux/amd64  # Add this line
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./.docker/storage/mysql/2025_03_22_backup.sql:/docker-entrypoint-initdb.d/backup.sql
    restart: unless-stopped

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://encounterthecross.test https://men.encounterthecross.test https://women.encounterthecross.test
      USE_FORWARDED_HEADERS: '1'
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    ports:
      - "3000:3000"  # Expose Mercure port
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
  ###< symfony/mercure-bundle ###

volumes:
  mysql_data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ${PWD}/.docker/storage/mysql
  ###> symfony/mercure-bundle ###
  mercure_data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ${PWD}/.docker/storage/mercure/data
  mercure_config:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ${PWD}/.docker/storage/mercure/config
  ###< symfony/mercure-bundle ###
