controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

tzunghaor_settings_editor:
    resource: '@TzunghaorSettingsBundle/config/routes.xml'
    prefix: '/admin/settings'

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health